export const product1 = {
  'id': 'MLA1376380831',
  'title': "Beginner's Guide To Silk Ribbon Embroidery : Re-issue, De Ann Cox. Editorial Search Press Ltd, Tapa Blanda En Inglés",
  'condition': 'new',
  'thumbnail_id': '970667-MLU70292220017_072023',
  'catalog_product_id': 'MLA24230250',
  'listing_type_id': 'gold_special',
  'permalink': 'https://www.mercadolibre.com.ar/beginners-guide-to-silk-ribbon-embroidery-re-issue-de-ann-cox-editorial-search-press-ltd-tapa-blanda-en-ingles/p/MLA24230250',
  'buying_mode': 'buy_it_now',
  'site_id': 'MLA',
  'category_id': 'MLA412445',
  'domain_id': 'MLA-BOOKS',
  'thumbnail': 'http://http2.mlstatic.com/D_970667-MLU70292220017_072023-I.jpg',
  'currency_id': 'ARS',
  'order_backend': 1,
  'price': 11332,
  'original_price': null,
  'sale_price': null,
  'sold_quantity': 0,
  'available_quantity': 1,
  'official_store_id': 3073,
  'official_store_name': 'LIBERATE',
  'use_thumbnail_id': true,
  'accepts_mercadopago': true,
  'tags': [],
  'shipping': {
    'logistic_type': 'fulfillment',
  },
  'stop_time': '2043-07-04T04:00:00.000Z',
  'seller': {},
  'seller_address': {},
  'address': {
    'state_name': 'Buenos Aires',
    'city_name': 'Beccar'
  },
  'attributes': [],
  'installments': {
    'quantity': 12,
    'amount': 13424.96,
  },
  'winner_item_id': null,
  'catalog_listing': true,
  'discounts': null,
  'promotions': [
  ],
  'inventory_id': null
};

export const product2 = {
  'id': 'MLA1458143106',
  'title': 'Complete Guide To Life Drawing, De Gottfried Bammes. Editorial Search Press Ltd, Tapa Blanda En Inglés',
  'condition': 'new',
  'thumbnail_id': '632680-MLU70085411951_062023',
  'catalog_product_id': 'MLA24052106',
  'listing_type_id': 'gold_special',
  'permalink': 'https://www.mercadolibre.com.ar/complete-guide-to-life-drawing-de-gottfried-bammes-editorial-search-press-ltd-tapa-blanda-en-ingles/p/MLA24052106',
  'buying_mode': 'buy_it_now',
  'site_id': 'MLA',
  'category_id': 'MLA412445',
  'domain_id': 'MLA-BOOKS',
  'thumbnail': 'http://http2.mlstatic.com/D_632680-MLU70085411951_062023-I.jpg',
  'currency_id': 'ARS',
  'order_backend': 2,
  'price': 66874,
  'original_price': null,
  'sale_price': null,
  'sold_quantity': 0,
  'available_quantity': 1,
  'official_store_id': 3073,
  'official_store_name': 'LIBERATE',
  'use_thumbnail_id': true,
  'accepts_mercadopago': true,
  'tags': [],
  'shipping': {
    'logistic_type': 'cross_docking',
  },
  'stop_time': '2043-07-19T04:00:00.000Z',
  'seller': {},
  'seller_address': {},
  'address': {
    'state_name': 'Buenos Aires',
    'city_name': 'Beccar'
  },
  'attributes': [],
  'installments': {
    'quantity': 12,
    'amount': 13424.96,
  },
  'winner_item_id': null,
  'catalog_listing': true,
  'discounts': null,
  'promotions': [
  ],
  'inventory_id': null
}